language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shahban/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true USERNAME/react-test npm test


after_sucess:
  - docker build -t shahban/multi-client ./client
  - docker build -t shahban/multi-client ./nginx
  - docker build -t shahban/multi-client ./server
  - docker build -t shahban/multi-client ./worker
  
  #Log in to the docker CLI
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to dockerhub
  - docker push shahban/multi-client
  - docker push shahban/multi-nginx
  - docker push shahban/multi-server
  - docker push shahban/multi-worker